### ISSUE TITLE
Help: scraping a list

### ISSUE THREAD

**Issue by flip111** [scrapinghub/portia#147] opened 2015-02-26 15:19 UTC
Suppose there is a webshop where products can have different specifications which can change per product. The specs are in a UL list. How can portia scrape the entire UL and put all the LI's as items?

**Comment by ruairif** [comment] 2015-02-26 15:24
You can try variants.

**Comment by flip111** [comment] 2015-02-26 15:40
I just tried that after your suggestion. What i did is clicked the first item, mapped it to a field and added it to variant #1. Then i clicked the second item, mapped it to the same field and also added it to variant #1. I noticed that not all items where now in the variant. So i tried again now clicking the first and last items. And all the specifications appeared in the variant.
I think this method would require me to find the product with the most specifications in order to make sure i can capture them all. Why can't i just click the `UL` and tell i want all the inner `LI`? I saw when editing an annotation that there is an interface to select parent elements, so that could be a start.

**Comment by flip111** [comment] 2015-02-26 15:43
Wow what a coincidence. I referenced the first github issue twice in my previous comment. And actually this issue from april 2014 is about exactly the same!!

**Comment by ruairif** [comment] 2015-02-26 16:48
The answer is in that thread too. If it doesn't work with variants then you'll have to wait until that issue is resolved unfortunately.
Soon is relative though so it could happen anytime :smile: 
Since this amounts to a duplicate of #1 I'll close this one.

**Closed by ruairif** 2015-02-26 16:48 UTC
