### ISSUE TITLE
Cant visit http://localhost:8000/

### ISSUE THREAD

**Issue by fakegit** [scrapinghub/portia#320] opened 2015-12-04 08:08 UTC
After installed vagrant and virtualbox on my win7 amd64 pc, I successfully launched the Ubuntu virtual machine.
![image](https://cloud.githubusercontent.com/assets/1928984/11584671/a2dd3e6a-9aa0-11e5-8434-850bb012dcb6.png)

However, when I visited http://localhost:8000/, I got this.
![image](https://cloud.githubusercontent.com/assets/1928984/11584722/365a79fa-9aa1-11e5-9891-23da71298f98.png)

What am i missing?

**Comment by nycreep** [comment] 2015-12-11 20:44
i get a black page as well ( although it says " No data received

ERR_EMPTY_RESPONSE" )

**Comment by vgvassilev** [comment] 2016-01-04 10:06
Seems a flavor of #331. Please see the remedy there ;)

**Comment by Gwai2Lo2** [comment] 2016-02-03 00:04
I installed portia with vagrant on Mac OSX, but can't access it.

I executed the 4 commands as I read that the current build has some flaws:

vagrant destroy
git fetch origin pull/330/head:pr-330
git checkout pr-330
vagrant up

but I also still can't access the

http://localhost:9001/

even though during the booting it says:

==> default: Forwarding ports...
    default: 9001 (guest) => 9001 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)

I can access the VM via

vagrant ssh

but I could not find out how to double confirm the forwarding ports in there or what to do in order to find the root cause for my problem.

Maybe somebody can help me out.

Thanks.

**Comment by vgvassilev** [comment] 2016-02-03 09:03
Please make sure you have slyd.conf pointing to 9001 because it is seems a bug.
```
 slyd.conf
@@ -3,5 +3,7 @@ start on vagrant-mounted
 stop on runlevel [!2345]
 
 chdir /vagrant/slyd
-exec bin/slyd -p 8000 --root ./dist
+script
+    PYTHONPATH=/vagrant/slyd:/vagrant/slybot bin/slyd -p 9002 --root ./dist
```

PS: PR #330 is already merged so the master *should* be fine ;)
-- Vassil

**Comment by Gwai2Lo2** [comment] 2016-02-03 14:08
Thanks vgvassilev

I have downloaded the latest version from here:

[](https://github.com/scrapinghub/portia)

but the slid.conf was still pointing to 9002 instead of 9001. Unfortunately I still can't access

http://localhost:9001/

Any other clue to get portia running? I'm trying already 3 days and still can't get it running.

**Comment by vgvassilev** [comment] 2016-02-03 14:09
Did destroy and rerun vagrant?

**Comment by Gwai2Lo2** [comment] 2016-02-03 14:10
yes

**Comment by vgvassilev** [comment] 2016-02-03 14:11
Log into the machine and check whether slyd is running and its log files. Check who is listening on port 9001.

**Comment by Gwai2Lo2** [comment] 2016-02-03 14:12
how do I do this? Sorry, I have quite limited knowledge in this. Thanks

**Comment by vgvassilev** [comment] 2016-02-03 14:18
vagrant ssh
what is the content of /etc/init/slyd.conf

**Comment by Gwai2Lo2** [comment] 2016-02-03 15:37
I finally made it, the trick was to reload vagrant as it seems that there was a conflict with a previous installation of portia

Thanks a lot

**Comment by psychok7** [comment] 2016-02-09 13:53
@vgvassilev @Youwotma i am still having this issue in Ubuntu 14.04 LTS with the current Master.

my `/etc/init/slyd.conf` is like this inside the vagrant:

```
description "slyd server"
start on vagrant-mounted
stop on runlevel [!2345]

chdir /vagrant/slyd
script
    PYTHONPATH=/vagrant/slyd:/vagrant/slybot bin/slyd -p 9002 --root ./dist
end script
respawn

```

the vagrant file:

```
# vim:ft=ruby

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.host_name = "portia"
	config.vm.provision :shell, :path => 'provision.sh', :args => ["install_deps", "install_splash", "install_python_deps", "configure_nginx", "configure_initctl"]
	config.vm.network "private_network", ip: "33.33.33.10"
	config.vm.network "forwarded_port", guest: 9002, host: 9002
	config.vm.provider "virtualbox" do |v|
		v.memory = 2048
 		v.cpus = 1
	end
end


```

**Comment by psychok7** [comment] 2016-02-15 17:02
tried both development and master branch and when i vagrant up for the first time i get:

```
==> default: Installing collected packages: slybot
==> default:   Running setup.py develop for slybot
==> default:     
==> default:     Creating /usr/local/lib/python2.7/dist-packages/slybot.egg-link (link to .)
==> default:     Adding slybot 0.12.1 to easy-install.pth file
==> default:     Installing slybot script to /usr/local/bin
==> default:     Installing portiacrawl script to /usr/local/bin
==> default:     
==> default:     Installed /vagrant/slybot
==> default: Successfully installed slybot
==> default: Cleaning up...
==> default: Executing command: configure_nginx
==> default: Executing command: configure_initctl
==> default: Starting slyd service
==> default: =====================
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

**Comment by JanAhrend** [comment] 2016-03-24 15:35
I am facing the same issue and error code as psychok7.  I can ssh into vagrant but cannot access the localhost front-end. 
Is there a way to work around this issue?

**Closed** 2016-06-21 10:57 UTC
